//AUTOGENERATED FILE FROM png2asset
#include <gb/cgb.h>
#include <stdint.h>

const uint16_t tetramino_graphic_palettes[4] = {
	RGB8(255, 255, 255), RGB8(255, 79, 114), RGB8(0, 0, 0), RGB8(0, 0, 0)
};

const uint8_t tetramino_graphic_tiles[16] = {
	0xff,0x00,0x81,0x00,
	0xbd,0x00,0xa5,0x00,
	0xa5,0x00,0xbd,0x00,
	0x81,0x00,0xff,0x00
};
