//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tetramino_graphic_H
#define METASPRITE_tetramino_graphic_H

#include <stdint.h>

#define tetramino_graphic_TILE_ORIGIN 0
#define tetramino_graphic_TILE_W 8
#define tetramino_graphic_TILE_H 8
#define tetramino_graphic_WIDTH 8
#define tetramino_graphic_HEIGHT 8
#define tetramino_graphic_TILE_COUNT 1
#define tetramino_graphic_PALETTE_COUNT 1
#define tetramino_graphic_COLORS_PER_PALETTE 4
#define tetramino_graphic_TOTAL_COLORS 4

extern const uint16_t tetramino_graphic_palettes[4];
extern const uint8_t tetramino_graphic_tiles[16];

#endif
