//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_game_scene_H
#define METASPRITE_game_scene_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define game_scene_TILE_ORIGIN 0
#define game_scene_TILE_W 8
#define game_scene_TILE_H 8
#define game_scene_WIDTH 160
#define game_scene_HEIGHT 144
#define game_scene_TILE_COUNT 85
#define game_scene_PALETTE_COUNT 8
#define game_scene_COLORS_PER_PALETTE 4
#define game_scene_TOTAL_COLORS 32
#define game_scene_MAP_ATTRIBUTES game_scene_map_attributes
#define game_scene_MAP_ATTRIBUTES_WIDTH 20
#define game_scene_MAP_ATTRIBUTES_HEIGHT 18
#define game_scene_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define game_scene_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char game_scene_map[360];
extern const unsigned char game_scene_map_attributes[360];

BANKREF_EXTERN(game_scene)

extern const uint16_t game_scene_palettes[32];
extern const uint8_t game_scene_tiles[1360];

#endif
